EXE =
LIB = .a
OBJ = .o

MAKE = make
AR = ar
ARFLAGS = -ruv
CAT = cat
CCS = $(CC)
CCP = mpicc
CCD = $(CC)

CLIBFLAGS =
CP = cp
FLEX = flex
LN = ln
MKDIR = mkdir -p
MV = mv
RANLIB = ranlib
BISON = bison
