{% set name = "kuristo" %}
{% set version = "0.6.1" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/andrsd/kuristo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 423d20b687abe5c826bc43f8687a5344a3ab15c380d7bb26fd3250c16218a233

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - pyaml
    - networkx
    - rich
    - jinja2
    - pydantic

test:
  imports:
    - kuristo

about:
  home: https://github.com/andrsd/kuristo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automation tool in python

extra:
  recipe-maintainers:
    - andrsd
