{% set name = "kuristo" %}
{% set version = "0.7.2" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/andrsd/kuristo
  git_rev: v{{ version }}

build:
  noarch: python
  number: {{ build }}
  script:
    - {{ PYTHON }} -m setuptools_scm > kuristo/_version.py
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10, <3.14
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >=3.10, <3.14
    - pyaml
    - networkx
    - rich
    - jinja2
    - pydantic

test:
  imports:
    - kuristo
  commands:
    - kuristo --help

about:
  home: https://github.com/andrsd/kuristo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automation tool in python

extra:
  recipe-maintainers:
    - andrsd
