{% set name = "occt" %}
{% set version = "7.9.0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V{{ version.replace(".", "_") }}.tar.gz
  sha256: 151b7a522ba8220aed3009e440246abbaf2ffec42672c37e9390096f7f2c098d

build:
  number: {{ build }}
  run_exports:
    # ABI changes between minor versions, see e.g.
    # https://github.com/conda-forge/occt-feedstock/issues/97
    - {{ pin_subpackage('occt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}           # [linux]
    - cmake
    - make
    - {{ cdt('libxi-devel') }}        # [linux]
    - {{ cdt('libxext-devel') }}      # [linux]
  host:
    - xorg-libxt                      # [linux]
    - rapidjson
  run:
    - xorg-libxt                      # [linux]
    - rapidjson

test:
  requires:
    - ninja
    - cmake
  files:
    - CMakeLists.txt
  commands:
    - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1-only
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - andrsd
