{% set version = "8.2.0" %}
{% set build = 3 %}

package:
  name: fprops
  version: {{ version }}

source:
  url: https://github.com/andrsd/fprops/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3d5e0c38f30d7f454a13b42c1d6b342c35b0bcbd12ba917d4a13cee463abe9f9

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pybind11
    - python {{ python }}
  host:
    - fmt 11.*
    - hdf5 1.14.* {{ mpi }}_*
    - eigen 3.4.*
    - python {{ python }}
    - zlib 1.3.*
  run:
    - fmt 11.*
    - eigen 3.4.*
    - hdf5 1.14.* {{ mpi }}_*
    - python {{ python }}
    - zlib 1.3.*

test:
  commands:
    - test -f $PREFIX/lib/libfprops$SHLIB_EXT # [unix]
    - test -f $PREFIX/include/fprops/fprops.h
  imports:
    - fprops
  requires:
    - pip

about:
  home: data['url']
  license: MIT
  summary: Fluid properties
  doc_url: https://andrsd.github.io/fprops

extra:
  recipe-maintainers:
    - andrsd
