{% set version = "1.1" %}
{% set build = 0 %}

package:
  name: fprops
  version: {{ version }}

source:
  url: https://github.com/andrsd/fprops/archive/refs/tags/v{{ version }}.tar.gz
  sha256: faf5950dcdc3071afa70cf72d7922b2578e675139a1431f3d7f4989004d98a8a

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pybind11
    - python {{ python }}
  host:
    - fmt 9.*
    - python {{ python }}
  run:
    - fmt 9.*
    - python {{ python }}

about:
  home: data['url']
  license: MIT
  summary: Fluid properties
  doc_url: https://andrsd.github.io/fprops

extra:
  recipe-maintainers:
    - andrsd
