{% set version = "2.0" %}
{% set build = 0 %}

package:
  name: fprops
  version: {{ version }}

source:
  url: https://github.com/andrsd/fprops/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2fc344ede8860c2d8bc9b5919ba6880ee2f4abf397985ebdac4244946282b327

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pybind11
    - python {{ python }}
  host:
    - fmt 9.*
    - python {{ python }}
  run:
    - fmt 9.*
    - python {{ python }}

about:
  home: data['url']
  license: MIT
  summary: Fluid properties
  doc_url: https://andrsd.github.io/fprops

extra:
  recipe-maintainers:
    - andrsd
