{% set version = "7.1.0" %}
{% set build = 0 %}

package:
  name: fprops
  version: {{ version }}

source:
  url: https://github.com/andrsd/fprops/archive/refs/tags/v{{ version }}.tar.gz
  sha256: adfaf2518e2a25a786cef596093ccca01cf9a6d2693e4bfbc1ea0ede38694ddc

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pybind11
    - python {{ python }}
  host:
    - fmt 9.*
    - hdf5 1.12.* {{ mpi }}_*
    - eigen 3.4.*
    - python {{ python }}
    - zlib
  run:
    - fmt 9.*
    - eigen 3.4.*
    - hdf5 1.12.* {{ mpi }}_*
    - python {{ python }}
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libfprops$SHLIB_EXT # [unix]
    - test -f $PREFIX/include/fprops/fprops.h
  imports:
    - fprops
  requires:
    - pip

about:
  home: data['url']
  license: MIT
  summary: Fluid properties
  doc_url: https://andrsd.github.io/fprops

extra:
  recipe-maintainers:
    - andrsd
