MACOSX_SDK_VERSION:    # [osx]
  - 10.12              # [osx and x86_64]
  - 11.0               # [osx and arm64]
c_compiler:             # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler:           # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler_version:
  - '14'
python_min:
  - '3.9'
  