{% set version = "5.4.1" %}
{% set build = 0 %}

package:
  name: meshio
  version: {{ version }}

source:
  url: https://github.com/andrsd/meshio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a3d9e506640acef31594b032e003330504b604b9aaa6ae06fadc363edb8774c3

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.20.0
    - rich

test:
  imports:
    - meshio
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/andrsd/meshio
  license: MIT
  license_file: LICENSE.txt
  summary: input/output for many mesh formats

extra:
  recipe-maintainers:
    - andrsd
