{% set version = "5.4.0" %}
{% set build = 0 %}

package:
  name: meshio
  version: {{ version }}

source:
  url: https://github.com/andrsd/meshio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7bd8c2f71ec509ee550a1e151f9faa93eab8ad141b542bb4ec0d0213263e5b65

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.20.0
    - rich

test:
  imports:
    - meshio
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/andrsd/meshio
  license: MIT
  license_file: LICENSE.txt
  summary: input/output for many mesh formats

extra:
  recipe-maintainers:
    - andrsd
