{% set version = "1.7.3" %}
{% set build = 0 %}

package:
  name: netcdf4
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf4-python/archive/refs/tags/v{{ version }}rel.tar.gz
  sha256: dff77ab20e26e43426dd19256e71aacbd4c92bfb172cc30e647c9e34b4c53828

build:
  skip: true  # [win]
  number: {{ build }}

  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4

requirements:
  build:
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
  host:
    - python {{ python }}
    - pip
    - numpy
    - cython >=0.19
    - cftime >=1.0.1
    # need to list hdf5 and libnetcdf twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - libnetcdf
    - mpi4py
    - setuptools >=61
    - setuptools_scm >=3.4
    - zlib
  run:
    - python {{ python }}
    - certifi
    - cftime
    - numpy
    # the 'nompi' build should work with both non-MPI and MPI variants of the
    # following libs
    - hdf5
    - libnetcdf
    - mpi4py

test:
  source_files:
    - test
  imports:
    - netCDF4
    - cftime
  requires:
    - cython
    - packaging
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h
    - cd test && export NO_NET=YES; python run_all.py

about:
  home: http://github.com/Unidata/netcdf4-python
  license: MIT
  license_file: LICENSE
  summary: Provides an object-oriented python interface to the netCDF version 4 library
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - andrsd
