MACOSX_SDK_VERSION:  # [osx]
  - 10.14            # [osx and x86_64]
  - 11.0             # [osx and arm64]
c_compiler:          # [osx]
  - clang_bootstrap  # [osx]
cxx_compiler:        # [osx]
  - clang_bootstrap  # [osx]