#!/bin/bash
set -ex

cmake ${CMAKE_ARGS} \
  -S ${SRC_DIR} -B build \
  -DCMAKE_INSTALL_PREFIX=${PREFIX} \
  -DCMAKE_BUILD_TYPE=Release \
  -DOCCA_ENABLE_METAL=OFF \
  -DOCCA_ENABLE_OPENCL=OFF \
  -DOCCA_ENABLE_OPENMP=ON \
  -DOCCA_ENABLE_DPCPP=OFF \
  -DOCCA_ENABLE_CUDA=OFF \
  -DOCCA_ENABLE_HIP=OFF \
  -DOCCA_ENABLE_FORTRAN=OFF \
  -DOCCA_ENABLE_TESTS=OFF \
  -DOCCA_ENABLE_EXAMPLES=OFF

cmake --build build --parallel ${CPU_COUNT}
cmake --build build -- install
