{% set name = "libocca" %}
{% set version = "2.0.0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/libocca/occa/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f2521901fed5d199193d54c7db4186479a974bdae92ac97779c47fa2bb68badd

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

test:
  commands:
    - test -f ${PREFIX}/include/occa.h            # [unix]
    - test -f ${PREFIX}/lib/libocca${SHLIB_EXT}   # [unix]

about:
  home: https://github.com/libocca/occa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Portable and vendor neutral framework for parallel programming on heterogeneous platforms.

extra:
  recipe-maintainers:
    - andrsd
