{% set version = "0.5.1" %}
{% set build = 1 %}

package:
  name: au
  version: {{ version }}

source:
  url: https://github.com/aurora-opensource/au/archive/refs/tags/{{ version }}.tar.gz
  sha256: 65675096bab253f81813760a5643810cb60c662a4fb2944bb49d77d9c11c85e8

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

tests:
  commands:
    - test -f $PREFIX/include/au/au.hh
    - test -f $PREFIX/lib/cmake/Au/AuConfig.cmake

about:
  summary: |
    A C++14-compatible physical units library with no dependencies and a single-file delivery
    option. Emphasis on safety, accessibility, performance, and developer experience.

extra:
  recipe-maintainers:
    - andrsd
