{% set name = "gperftools" %}
{% set version = "2.15" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gperftools/gperftools/releases/download/gperftools-{{ version }}/gperftools-{{ version }}.tar.gz
  sha256: c69fef855628c81ef56f12e3c58f2b7ce1f326c0a1fe783e5cae0b88cbbe9a80

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ pin_compatible('libunwind', max_pin='x.x') }}  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - gnuconfig  # [unix]
  host:
    - libunwind  # [linux]
  run:
    - perl

test:
  commands:
    - pprof --help

about:
  home: https://github.com/gperftools/gperftools
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: The fastest malloc we have seen; works particularly well with threads and STL
  description: |
    gperftools is a collection of a high-performance multi-threaded
    malloc() implementation, plus some pretty nifty performance analysis
    tools.
  doc_url: https://github.com/gperftools/gperftools/wiki
  dev_url: https://github.com/gperftools/gperftools

extra:
  recipe-maintainers:
    - andrsd
