{% set version = "0.6" %}
{% set build = 1 %}

package:
  name: gmsh2exo
  version: {{ version }}

source:
  url: https://github.com/andrsd/gmsh2exo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ecaa6890e22192947f196bd3ce925956ecbbc87428ace517fe8603b52fd7a4f2

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - cmake
    - make
    - flex
    - {{ compiler('cxx') }}
  host:
    - fmt 9.*
    - exodusii 2022.08.* {{ mpi }}_*
  run:
    - fmt 9.*
    - exodusii 2022.08.* {{ mpi }}_*

test:
  commands:
    - test -f "${PREFIX}/bin/gmsh2exo"

about:
  summary: |
    Convert GMSH mesh into ExodusII

extra:
  recipe-maintainers:
    - andrsd
