{% set version = "0.7" %}
{% set build = 0 %}

package:
  name: gmsh2exo
  version: {{ version }}

source:
  url: https://github.com/andrsd/gmsh2exo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04bf4e30b8cddf52531dc52f6b94f890b0261a708acda31c0007abc2ba788d40

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - cmake
    - make
    - flex
    - {{ compiler('cxx') }}
  host:
    - fmt 9.*
    - flex
    - exodusii 2022.08.* {{ mpi }}_*
  run:
    - fmt 9.*
    - exodusii 2022.08.* {{ mpi }}_*

test:
  commands:
    - test -f "${PREFIX}/bin/gmsh2exo"
    - gmsh2exo --version

about:
  summary: |
    Convert GMSH mesh into ExodusII

extra:
  recipe-maintainers:
    - andrsd
