{% set version = "0.10" %}
{% set commit = "12d1556505c244059741466dec3e012af4974e3b" %}
{% set build = 0 %}

package:
  name: gmsh2exo
  version: {{ version }}

source:
  url: https://github.com/andrsd/gmsh2exo/archive/{{ commit }}.tar.gz
  sha256: f388cc8c6fea950f9f574fe3352211ef6dd618b160ab71a9977e74ae295bfb7b

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - cmake
    - make
    - flex
    - {{ compiler('cxx') }}
  host:
    - fmt 11.*
    - flex
    - exodusii 2022.10.* {{ mpi }}_*
  run:
    - fmt 11.*
    - exodusii 2022.10.* {{ mpi }}_*

test:
  commands:
    - test -f "${PREFIX}/bin/gmsh2exo"
    - gmsh2exo --version

about:
  summary: |
    Convert GMSH mesh into ExodusII

extra:
  recipe-maintainers:
    - andrsd
