MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64 and osx]

python:
  - 3.9.*
  - 3.10.*

numpy:
  - 1.26

occt:
  - 7.7
