{% set version = "4.9.1" %}
{% set build = 1 %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 4ee8d5f6b50a1eb4ad4c10f24531e36261fd1882410fb08435eb2ddfd49a0908

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - autoconf
    - automake
    - m4
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.12.* {{ mpi }}_*
    - zlib 1.2.*
  host:
    - {{ mpi }}
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.12.* {{ mpi }}_*
    - zlib 1.2.*
  run:
    - {{ mpi }}
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.12.* {{ mpi }}_*
    - zlib 1.2.*

test:
  command:
    - test -f $PREFIX/lib/libnetcdf$SHLIB_EXT
    - test -f $PREFIX/lib/libnetcdf.settings
    - test -f $PREFIX/include/netcdf.h

about:
  summary: netCDF is an interface for scientific data access.

extra:
  recipe-maintainers:
    - andrsd
