{% set version = "4.9.2" %}
{% set build = 2 %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  url: https://web.cels.anl.gov/projects/petsc/download/externalpackages/netcdf-c-4.9.2-p1.tar.gz
  sha256: f0da771cddd71d8555f0896272145ba5b88800bfce6022615fa9d10d6ef8e356

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - autoconf
    - automake
    - m4
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.14.* {{ mpi }}_*
    - zlib 1.3.*
  host:
    - {{ mpi }}
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.14.* {{ mpi }}_*
    - zlib 1.3.*
  run:
    - {{ mpi }}
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.14.* {{ mpi }}_*
    - zlib 1.3.*

test:
  command:
    - test -f $PREFIX/lib/libnetcdf$SHLIB_EXT
    - test -f $PREFIX/lib/libnetcdf.settings
    - test -f $PREFIX/include/netcdf.h

about:
  summary: netCDF is an interface for scientific data access.

extra:
  recipe-maintainers:
    - andrsd
