{% set version = "2.1.0" %}
{% set build = 2 %}

package:
  name: mpicpp-lite
  version: {{ version }}

source:
  url: https://github.com/andrsd/mpicpp-lite/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 38e8742f8a56c5f627bfe77ef600c8067af3efdb09992ade2aeba0546c2eb931

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ mpi }}
  host:
    - {{ mpi }}
  run:
    - {{ mpi }}

test:
  commands:
    - test -f $PREFIX/include/mpicpp-lite/mpicpp-lite.h

about:
  home: data['url']
  license: MIT
  summary: Light C++ wrapper around MPI
  doc_url: https://andrsd.github.io/mpicpp-lite/

extra:
  recipe-maintainers:
    - andrsd
