{% set version = "1.6.0" %}
{% set build = 1 %}

package:
  name: mpicpp-lite
  version: {{ version }}

source:
  url: https://github.com/andrsd/mpicpp-lite/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dad3bc3cd18ff58c3ec867024061c79149d8a01a4abb20a48ecefb01de5a9d50

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - fmt 9.*
    - {{ mpi }}
  host:
    - fmt 9.*
    - {{ mpi }}
  run:
    - fmt 9.*
    - {{ mpi }}

test:
  commands:
    - test -f $PREFIX/include/mpicpp-lite/mpicpp-lite.h

about:
  home: data['url']
  license: MIT
  summary: Light C++ wrapper around MPI
  doc_url: https://andrsd.github.io/mpicpp-lite/

extra:
  recipe-maintainers:
    - andrsd
