{% set version = "2.5.0" %}
{% set build = 0 %}

package:
  name: mpicpp-lite
  version: {{ version }}

source:
  url: https://github.com/andrsd/mpicpp-lite/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 41ebd9057ad0c7c42fc640d6277bc2f00887c1f826f0ea21b19ec07964add08f

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - {{ mpi }}
  host:
    - {{ mpi }}
  run:
    - {{ mpi }}

test:
  commands:
    - test -f $PREFIX/include/mpicpp-lite/mpicpp-lite.h

about:
  home: data['url']
  license: MIT
  summary: Light C++ wrapper around MPI
  doc_url: https://andrsd.github.io/mpicpp-lite/

extra:
  recipe-maintainers:
    - andrsd
