MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [x86_64 and osx]
  - 11.3                                                    # [arm64 and osx]

mpi:
  - mpich

pin_run_as_build:
  mpich: x.x
  openmpi: x.x
