MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64 and osx]

mpi:
  - mpich
  - openmpi

pin_run_as_build:
  mpich: x.x
  openmpi: x.x
