{% set version = "4.0.3-p9" %}
{% set build = 4 %}

package:
  name: parmetis
  version: {{ version|replace('-', '.') }}

source:
  url: https://bitbucket.org/petsc/pkg-parmetis/get/v{{ version }}.tar.gz
  sha256: 612717e85992c984f09b0f5670be421bbb90a4c04145ab5b9a3358b92765d891
  patches:
    - files/cmake-version-3.16.patch

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ mpi }}
  host:
    - {{ mpi }}
    - metis 5.1.0.p12
  run:
    - {{ mpi }}
    - metis 5.1.0.p12

test:
  commands:
    - test -f "${PREFIX}/include/parmetis.h"
    - test -f "${PREFIX}/lib/libparmetis.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libparmetis.so"  # [linux]

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
  license: Non-free for commercial use
  license_file: LICENSE.txt
  summary: 'ParMETIS - Parallel Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    ParMETIS is an MPI-based parallel library that implements a
    variety of algorithms for partitioning unstructured graphs,
    meshes, and for computing fill-reducing orderings of sparse
    matrices. ParMETIS extends the functionality provided by METIS and
    includes routines that are especially suited for parallel AMR
    computations and large scale numerical simulations. The algorithms
    implemented in ParMETIS are based on the parallel multilevel k-way
    graph-partitioning, adaptive repartitioning, and parallel
    multi-constrained partitioning schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/manual.pdf

extra:
  recipe-maintainers:
    - andrsd
