MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [x86_64 and osx]
  - 11.3                                                    # [arm64 and osx]

mpi:
  - mpich
  - openmpi

blas:
  - openblas  # [linux]
  - libaccelerate-osx  # [osx]

lapack:
  - openblas  # [linux]
  - libaccelerate-osx  # [osx]
