{% set version = "7.0.3" %}
{% set build = 1 %}

package:
  name: ptscotch
  version: {{ version }}

source:
  url: http://ftp.mcs.anl.gov/pub/petsc/externalpackages/scotch-v{{ version }}.tar.gz
  sha256: 5b5351f0ffd6fcae9ae7eafeccaa5a25602845b9ffd1afb104db932dd4d4f3c5

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ mpi }}
    - bison
    - flex
    - parmetis 4.0.* {{ mpi }}_*
  host:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - parmetis 4.0.* {{ mpi }}_*
    - zlib
  run:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - parmetis 4.0.* {{ mpi }}_*
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libesmumps.a
    - test -f $PREFIX/lib/libptesmumps.a
    - test -f $PREFIX/lib/libptscotch.a
    - test -f $PREFIX/lib/libptscotcherr.a
    - test -f $PREFIX/lib/libptscotchparmetisv3.a
    - test -f $PREFIX/lib/libscotch.a
    - test -f $PREFIX/lib/libscotcherr.a

about:
  home: https://www.labri.fr/perso/pelegrin/scotch/
  license: CECILL-C
  license_file: doc/CeCILL-C_V1-en.txt
  summary: |
    SCOTCH: Static Mapping, Graph, Mesh and Hypergraph Partitioning, and Parallel and Sequential Sparse Matrix Ordering 
    Package
  description: |
    Software package and libraries for sequential and parallel graph partitioning, static mapping and clustering, 
    sequential mesh and hypergraph partitioning, and sequential and parallel sparse matrix block ordering.
  doc_url: http://gforge.inria.fr/docman/?group_id=248&dirid=326
  dev_url: https://gitlab.inria.fr/scotch/scotch

extra:
  recipe-maintainers:
    - andrsd
