{% set name = "viennacl" %}
{% set version = "1.7.1" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/viennacl/viennacl-dev/archive/refs/tags/release-1.7.1.tar.gz
  sha256: dddb8d406b21de454ae7b960a49e9f58dab49bec578574213bcaf879f3172df2

  patches:
    - files/cmake.patch

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/cmake/viennacl/ViennaCLConfig.cmake
    - test -f $PREFIX/include/viennacl/vector.hpp

about:
  home: https://viennacl.sourceforge.net/index.html
  license: MIT
  license_file: LICENSE
  summary: Generate documentation from source code

  description: |
    ViennaCL is a free open-source linear algebra library for computations on many-core 
    architectures (GPUs, MIC) and multi-core CPUs. The library is written in C++ and supports
    CUDA, OpenCL, and OpenMP (including switches at runtime).
  doc_url: https://viennacl.sourceforge.net/viennacl-documentation.html
  dev_url: https://github.com/viennacl/viennacl-dev

extra:
  recipe-maintainers:
    - andrsd
