{% set version = "1.14.6" %}
{% set maj_min_patch_ver = "_".join(version.split(".")) %}
{% set maj_min_ver = "_".join(version.split(".")[:2]) %}
{% set build = 1 %}

package:
  name: hdf5
  version: {{ version }}

source:
  url: https://support.hdfgroup.org/releases/hdf5/v{{ maj_min_ver }}/v{{ maj_min_patch_ver }}/downloads/hdf5-{{ version }}.tar.gz
  sha256: e4defbac30f50d64e1556374aa49e574417c9e72c6b1de7a4ff88c4b1bea6e9b

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true   # [win]

requirements:
  build:
    - gnuconfig                    # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.2.2                # [win]
    - autoconf                     # [not win]
    - automake                     # [not win]
    - libtool                      # [not win]
    - make                         # [not win]
    - ninja                        # [win]
    - {{ mpi }}
  host:
    - {{ mpi }}
    - libcurl
    - zlib 1.3.*
  run:
    - {{ mpi }}
    - zlib 1.3.*

about:
  home: http://www.hdfgroup.org/HDF5/
  license: LicenseRef-HDF5
  license_family: BSD
  license_file: COPYING
  summary: HDF5 is a data model, library, and file format for storing and managing data
  dev_url: https://github.com/HDFGroup/hdf5
  doc_url: https://portal.hdfgroup.org/display/HDF5/HDF5

extra:
  recipe-maintainers:
    - andrsd
