{% set version = "1.12.1" %}
{% set maj_min_ver = ".".join(version.split(".")[:2]) %}
{% set build = 0 %}

package:
  name: hdf5
  version: {{ version }}

source:
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-{{ maj_min_ver }}/hdf5-{{ version }}/src/hdf5-{{ version }}.tar.gz
  sha256: 79c66ff67e666665369396e9c90b32e238e501f345afd2234186bfb8331081ca

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.2.2  # [win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - make  # [not win]
    - ninja  # [win]
    - {{ mpi }}
  host:
    - {{ mpi }}
    - libcurl
    - zlib 1.2.*
  run:
    - {{ mpi }}
    - zlib 1.2.*

about:
  home: http://www.hdfgroup.org/HDF5/
  license: LicenseRef-HDF5
  license_family: BSD
  license_file: COPYING
  summary: HDF5 is a data model, library, and file format for storing and managing data
  dev_url: https://github.com/HDFGroup/hdf5
  doc_url: https://portal.hdfgroup.org/display/HDF5/HDF5

extra:
  recipe-maintainers:
    - andrsd
