MACOSX_SDK_VERSION: # [osx]
  - 10.14 # [osx and x86_64]
  - 11.0 # [osx and arm64]

c_compiler: # [osx]
  - clang_bootstrap # [osx]
cxx_compiler: # [osx]
  - clang_bootstrap # [osx]
cxx_compiler_version:
  - "16"

python_min:
  - "3.9"

# Starting from LLVM 14, the ABI of libclang doesn't necessarily
# match the major version anymore - cf. #170 and
# https://github.com/llvm/llvm-project/issues/54004
libclang_soversion:
  - 13

# keep for use with root when it catches up
variant:
  - default
  - hcc # [linux]
