MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [osx and x86_64]
  - 11.3                                                    # [osx and arm64]

blas:
  - libblas  # [linux]
  - libaccelerate-osx  # [osx]

lapack:
  - liblapack  # [linux]
  - libaccelerate-osx  # [osx]
