macos_machine:
  - arm64-apple-darwin20.0.0
cross_platform:
  - osx-arm64
uname_machine:
  - arm64

c_compiler:             # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler:           # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler_version:   # [osx]
  - '16'                # [osx]

MACOSX_SDK_VERSION:     # [osx]
  - 10.14               # [osx and x86_64]
  - 11.0                # [osx and arm64]

llvm_version:
  - 16.0
  - 18.1

zip_keys:
  -
    - macos_machine
    - cross_platform
    - uname_machine
