{% set name = "libceed" %}
{% set version = "0.12.0" %}
{% set commit = "4018a20a98d451fac24765d3ddb936861647ce8d" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/CEED/libCEED/archive/{{ commit }}.tar.gz
  sha256: 4c642ae1563e0363aa48f5d794832ad6e9716789405e33511213b837d1528a23

build:
  number: {{ build }}
  skip: true # [win]

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('fortran') }}  # [linux]

test:
  commands:
    - test -f ${PREFIX}/include/ceed.h            # [unix]
    - test -f ${PREFIX}/lib/libceed${SHLIB_EXT}   # [unix]

about:
  home: https://github.com/CEED/libCEED/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Code for Efficient Extensible Discretizations

extra:
  recipe-maintainers:
    - andrsd
