{% set version = "2022.10.14" %}
{% set build = 0 %}

package:
  name: exodusii
  version: {{ version }}

source:
  url: https://github.com/sandialabs/seacas/archive/v{{ version | replace('.', '-') }}.tar.gz
  sha256: cde91e7561d2352045d669a25bdf46a604d85ed1ea7f3f5028004455e4ce9d56

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ mpi }}
    - cmake
    - make
  host:
    - {{ mpi }}
    - libnetcdf 4.9.* {{ mpi }}_*
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.12.* {{ mpi }}_*
    - fmt 9.*
  run:
    - {{ mpi }}
    - libnetcdf 4.9.* {{ mpi }}_*
    - libpnetcdf 1.12.* {{ mpi }}_*
    - hdf5 1.12.* {{ mpi }}_*
    - fmt 9.*

test:
  commands:
    - test -f $PREFIX/lib/libexoIIv2for32$SHLIB_EXT
    - test -f $PREFIX/lib/libexoIIv2for32.a
    - test -f $PREFIX/lib/libexodus_for$SHLIB_EXT
    - test -f $PREFIX/lib/libexodus_for.a
    - test -f $PREFIX/lib/libexodus$SHLIB_EXT
    - test -f $PREFIX/lib/libexodus.a
    - test -f $PREFIX/lib/libsupes$SHLIB_EXT
    - test -f $PREFIX/lib/libsuplib_cpp$SHLIB_EXT
    - test -f $PREFIX/lib/libsuplib_c$SHLIB_EXT
    - test -f $PREFIX/lib/libsuplib$SHLIB_EXT
    - test -f $PREFIX/include/exodusII.h
    - test -f $PREFIX/include/exodusII_par.h
    - test -f $PREFIX/include/exodus_config.h
    - test -f $PREFIX/include/exodusII.inc
    - test -f $PREFIX/bin/exodiff
    - test -f $PREFIX/bin/exotxt

about:
  home: https://github.com/sandialabs/seacas
  summary: |
    Exodus is a model developed to store and retrieve data for finite element analyses.
  license: LicenseRef-NTESS
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andrsd
