{% set version = "0.5.0" %}
{% set build = "0" %}

package:
  name: figura
  version: {{ version }}

source:
  url: https://github.com/andrsd/figura/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e4b41307f54c46ba751b7689e17ba465b4413a2b1a8ef96616562a63d4fc895a

build:
  number: {{ build }}
  script: ${PYTHON} -m pip install . --no-deps -vv

requirements:
  build:
    - make
  host:
    - python {{ python }}
    - setuptools
    - pythonocc-core >=7.6.*
    - multimethod >=1.9.*
  run:
    - python
    - pythonocc-core >=7.6.*
    - multimethod >=1.9.*

about:
  home: https://github.com/andrsd/figura
  license: MIT
  license_file: LICENSE
  summary: User-friendly python scripting for creating parametrical 3D models
  doc_url: https://andrsd.github.io/figura

extra:
  recipe-maintainers:
    - andrsd
