{% set version = "0.4.2" %}
{% set build = "0" %}

package:
  name: figura
  version: {{ version }}

source:
  url: https://github.com/andrsd/figura/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7f4b9c9d90966d78c29fbe0c9edde9b43a60b93b519a35bd1670f94490f5de18

build:
  number: {{ build }}
  script: ${PYTHON} -m pip install . --no-deps -vv

requirements:
  build:
    - make
  host:
    - python {{ python }}
    - setuptools
    - pythonocc-core 7.6.*
    - multimethod 1.9.*
  run:
    - python
    - pythonocc-core 7.6.*
    - multimethod 1.9.*

about:
  home: https://github.com/andrsd/figura
  license: MIT
  license_file: LICENSE
  summary: User-friendly python scripting for creating parametrical 3D models
  doc_url: https://andrsd.github.io/figura

extra:
  recipe-maintainers:
    - andrsd
