{% set version = "7.1.17" %}
{% set build = 0 %}

package:
  name: pygmsh
  version: {{ version }}

source:
  url: https://github.com/nschloe/pygmsh/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9c9c0fb507eb5c0d0f1f64a23909b3bda25652df737e935ea9336b08773afc4e

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python 3.9
    - pip
    - flit-core
    - gmsh-cli
    - python-gmsh
    - meshio >=4.3.2
    - numpy >=1.20.0
    - rich
  run:
    - python 3.9
    - gmsh-cli
    - python-gmsh
    - meshio >=4.3.2
    - numpy >=1.20.0
    - rich

test:
  imports:
    - pygmsh
  requires:
    - pip

about:
  home: https://github.com/nschloe/pygmsh
  license: GPL-3
  license_file: LICENSE.txt
  summary: Gmsh for Python

extra:
  recipe-maintainers:
    - andrsd
