{% set version = "2.28.0" %}
{% set build = 1 %}

package:
  name: hypre
  version: {{ version }}

source:
  url: https://github.com/hypre-space/hypre/archive/v{{ version }}.tar.gz
  sha256: 2eea68740cdbc0b49a5e428f06ad7af861d1e169ce6a12d2cf0aa2fc28c4a2ae

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ mpi }}
  host:
    - libblas
    - liblapack
    - {{ mpi }}
  run:
    - libblas
    - liblapack

test:
  commands:
    - test -f $PREFIX/include/HYPRE.h
    - test -f $PREFIX/lib/libHYPRE.dylib  # [osx]
    - test -f $PREFIX/lib/libHYPRE.so  # [linux]

about:
  home: https://www.llnl.gov/casc/hypre/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYRIGHT
  summary: high performance preconditioners for sparse linear systems
  description: |
    HYPRE is a library of high performance preconditioners and solvers featuring
    multigrid methods for the solution of large, sparse linear systems of equations
    on massively parallel computers.
  dev_url: https://github.com/hypre-space/hypre
  doc_url: https://hypre.readthedocs.io

extra:
  recipe-maintainers:
    - andrsd
