{% set version = "24.07.0" %}
{% set build = "0" %}

package:
  name: formo
  version: {{ version }}

source:
  url: https://github.com/andrsd/formo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b92321511b9d8f8f37de72aac88950bdb2f06fe9b0d5d146aa631ecb54df25d5

build:
  number: {{ build }}

requirements:
  build:
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python {{ python }}
    - setuptools
    - occt >=7.7.*
    - fmt >=9
    - pybind11
  run:
    - python
    - occt >=7.7.*
    - fmt >=9

about:
  home: https://github.com/andrsd/formo
  license: MIT
  license_file: LICENSE
  summary: User-friendly python scripting for creating parametrical 3D models
  doc_url: https://andrsd.github.io/formo

extra:
  recipe-maintainers:
    - andrsd
