{% set version = "25.09.0" %}
{% set build = 0 %}

package:
  name: formo
  version: {{ version }}

source:
  url: https://github.com/andrsd/formo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2394ee1d22a31744e6f8091858f3e985ff87b5a51218c7b497cf419a88d209d3

build:
  number: {{ build }}

requirements:
  build:
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python {{ python }}
    - setuptools
    - occt >=7.9.*
    - fmt 11.*
    - pybind11
  run:
    - python
    - occt >=7.9.*
    - fmt 11.*

about:
  home: https://github.com/andrsd/formo
  license: MIT
  license_file: LICENSE
  summary: User-friendly python scripting for creating parametrical 3D models
  doc_url: https://andrsd.github.io/formo

extra:
  recipe-maintainers:
    - andrsd
