{% set version = "25.06.0" %}
{% set build = "0" %}

package:
  name: formo
  version: {{ version }}

source:
  url: https://github.com/andrsd/formo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3321a16b32dc8655f85afe9facf7867249435706fb0625d5c7809f61b8e7a44b

build:
  number: {{ build }}

requirements:
  build:
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python {{ python }}
    - setuptools
    - occt >=7.9.*
    - fmt >=9
    - pybind11
  run:
    - python
    - occt >=7.9.*
    - fmt >=9

about:
  home: https://github.com/andrsd/formo
  license: MIT
  license_file: LICENSE
  summary: User-friendly python scripting for creating parametrical 3D models
  doc_url: https://andrsd.github.io/formo

extra:
  recipe-maintainers:
    - andrsd
