{% set version = "2.0.0" %}
{% set build = 0 %}

package:
  name: krado
  version: {{ version }}

source:
  url: https://github.com/andrsd/krado/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1ee4fa0f3e70d34b85592953a8a69afe1918f5ba74a2b2ea1da466fa3eb1bd54

build:
  number: {{ build }}

requirements:
  build:
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python {{ python }}
    - setuptools
    - exodusiicpp =3.*
    - occt >=7.9.*
    - eigen >=3.4.*
    - boost >=1.70
    - fmt 11.*
    - spdlog =1.*
    - pybind11
  run:
    - python
    - exodusiicpp =3.*
    - occt >=7.9.*
    - fmt 11.*
    - spdlog =1.*

about:
  home: https://github.com/andrsd/krado
  license: MIT
  license_file: LICENSE
  summary: Mesh manipulation package
  doc_url: https://andrsd.github.io/krado

extra:
  recipe-maintainers:
    - andrsd
