{% set version = "2.3.0" %}
{% set build = 4 %}

package:
  name: krado
  version: {{ version }}

source:
  url: https://github.com/andrsd/krado/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ac22c51d05d0e787f9a5e04d8153c556ceeee8e08a4532357af641b3db751416

build:
  number: {{ build }}

requirements:
  build:
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python {{ python }}
    - setuptools
    - exodusiicpp =3.*
    - occt =7.9.*
    - eigen =3.4.*
    - libboost-devel =1.88.*
    - fmt 11.*
    - spdlog =1.*
    - pybind11
  run:
    - python
    - exodusiicpp =3.*
    - occt =7.9.*
    - fmt 11.*
    - spdlog =1.*

about:
  home: https://github.com/andrsd/krado
  license: MIT
  license_file: LICENSE
  summary: Mesh manipulation package
  doc_url: https://andrsd.github.io/krado

extra:
  recipe-maintainers:
    - andrsd
