MACOSX_DEPLOYMENT_TARGET:   # [osx]
  - 10.15                   # [x86_64 and osx]
  - 11.3                    # [arm64 and osx]

cxx_compiler:
  - gxx                     # [linux]
  - clangxx                 # [osx]
cxx_compiler_version:
  - 14                      # [linux]
  - 20                      # [osx]


fortran_compiler:
  - gfortran                # [linux]
fortran_compiler_version:
  - 14                      # [linux]
  - 11                      # [osx]

zip_keys:
- - cxx_compiler_version
  - fortran_compiler_version