{% set version = "3.0.0" %}
{% set build = 3 %}

package:
  name: exodusiicpp
  version: {{ version }}

source:
  url: https://github.com/andrsd/exodusIIcpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 79985573a1477a60e69731faa9f73a47ad19899a909d800ba45c74e6d690868b

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - cmake
    - make
  host:
    - exodusii 2024.06.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 11.*
  run:
    - exodusii 2024.06.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 11.*

about:
  summary: |
    C++17 wrapper around ExodusII

extra:
  recipe-maintainers:
    - andrsd
