{% set version = "1.9" %}
{% set build = 0 %}

package:
  name: exodusiicpp
  version: {{ version }}

source:
  url: https://github.com/andrsd/exodusIIcpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3ca864b6ecafed6c6fb53c3d118095d93de97db70f2a1a23884a4b4678acf8c5

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - cmake
    - make
  host:
    - exodusii 2022.08.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 9.*
  run:
    - exodusii 2022.08.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 9.*

about:
  summary: |
    C++17 wrapper around ExodusII

extra:
  recipe-maintainers:
    - andrsd
