{% set version = "1.7" %}
{% set build = 0 %}

package:
  name: exodusiicpp
  version: {{ version }}

source:
  url: https://github.com/andrsd/exodusIIcpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 437aa8a668d49783ef1841b653b264a5923191282ea96b90985b10030173822f

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - cmake
    - make
  host:
    - exodusii 2022.08.* {{ mpi }}_*
    - yaml-cpp
    - fmt 9.*
  run:
    - exodusii 2022.08.* {{ mpi }}_*
    - yaml-cpp
    - fmt 9.*

about:
  summary: |
    C++17 wrapper around ExodusII

extra:
  recipe-maintainers:
    - andrsd
