{% set version = "2.0.1" %}
{% set build = 0 %}

package:
  name: exodusiicpp
  version: {{ version }}

source:
  url: https://github.com/andrsd/exodusIIcpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 38e64574c5d39127c6de668ae0477e26caa67d095385795b8e94b8786e06c017

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - cmake
    - make
  host:
    - exodusii 2022.10.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 9.*
  run:
    - exodusii 2022.10.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 9.*

about:
  summary: |
    C++17 wrapper around ExodusII

extra:
  recipe-maintainers:
    - andrsd
