{% set version = "1.6" %}
{% set build = 1 %}

package:
  name: exodusiicpp
  version: {{ version }}

source:
  url: https://github.com/andrsd/exodusIIcpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2f5e0f56752db7cc044e4dd255ceb56c8b22e02dc245d26348ae430115ca60ce

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - cmake
    - make
  host:
    - exodusii 2022.08.* {{ mpi }}_*
    - fmt 9.*
  run:
    - exodusii 2022.08.* {{ mpi }}_*
    - fmt 9.*

about:
  summary: |
    C++17 wrapper around ExodusII

extra:
  recipe-maintainers:
    - andrsd
