{% set version = "3.1.0" %}
{% set build = 2 %}

package:
  name: exodusiicpp
  version: {{ version }}

source:
  url: https://github.com/andrsd/exodusIIcpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d8c18aabf4d58b4b46f6586e463a8cdb626db472b3ebe61491ea2a16392c2112

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - cmake
    - make
  host:
    - exodusii 2024.06.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 11.*
  run:
    - exodusii 2024.06.* {{ mpi }}_*
    - yaml-cpp 0.8.*
    - fmt 11.*

tests:
  commands:
    - test -f $PREFIX/lib/cmake/exodusiicpp/exodusiicpp-config-version.cmake
    - test -f $PREFIX/lib/cmake/exodusiicpp/exodusiicpp-config.cmake
    - test -f $PREFIX/lib/cmake/exodusiicpp/exodusiicpp-targets-release.cmake
    - test -f $PREFIX/lib/cmake/exodusiicpp/exodusiicpp-targets.cmake
    - test -f $PREFIX/lib/cmake/exodusiicpp/FindExodusII.cmake

about:
  summary: |
    C++17 wrapper around ExodusII

extra:
  recipe-maintainers:
    - andrsd
