{% set version = "4.1.0" %}
{% set build = 0 %}
{% set mpi = mpi or 'mpich' %}

package:
  name: mpi4py
  version: {{ version }}

source:
  url: https://github.com/mpi4py/mpi4py/releases/download/{{ version }}/mpi4py-{{ version }}.tar.gz
  sha256: 817492796bce771ccd809a6051cf68d48689815493b567a696ce7679260449cd

build:
  number: {{ build }}
  script:
    - {{ PYTHON }} conf/cythonize.py
    - export OPAL_PREFIX=$PREFIX    # [mpi == "openmpi"]
    - {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  skip: true  # [win32]

requirements:
  build:
    - {{ compiler('c') }}
    {% if build_platform != target_platform %}
    - python {{ python }}
    - cython
    - cross-python_{{ target_platform }}
    - {{ mpi }}
    {% endif %}
  host:
    - python {{ python }}
    - pip
    - setuptools
    - python-build
    - cython
    - {{ mpi }}
  run:
    - python {{ python }}
    - {{ mpi }}
  run_exports:
    - {{ pin_subpackage("mpi4py", max_pin="x") }}

tests:
  - python:
      imports:
        - mpi4py
        - mpi4py.MPI
        - mpi4py.futures
        - mpi4py.util.dtlib
        - mpi4py.util.pkl5
        - mpi4py.util.pool
        - mpi4py.util.sync

about:
  home: https://mpi4py.github.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface (MPI)
    standard for the Python programming language, allowing any Python program
    to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://github.com/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - andrsd
