cuda_compiler:
  - None

cuda_compiler_version:
  - None

cxx_compiler_version:
  - 16                 # [osx]
  - 18                 # [osx]
  - 20                 # [osx]
  - 11                 # [linux]

libcxx_version:
  - 16                 # [osx]
  - 16                 # [osx]
  - 20                 # [osx]
  - 11                 # [linux]

ROCM_COMPILATION:
  - "disabled"

zip_keys:
  -
    - cxx_compiler_version
    - libcxx_version
