CBUILD:
  - x86_64-conda-linux-gnu       # [linux64]
  - arm64-apple-darwin20.0.0     # [osx and arm64]

MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.9                   # [osx and x86_64]
  - 11.0                   # [osx and arm64]

version:
  - 16.0.6

# everything below is zipped
cross_target_platform:
  - osx-arm64
macos_machine:
  - arm64-apple-darwin20.0.0
uname_machine:
  - arm64
meson_cpu_family:
  - aarch64
uname_kernel_release:
  - 20.0.0
FINAL_PYTHON_SYSCONFIGDATA_NAME:
  - _sysconfigdata_arm64_apple_darwin20_0_0

zip_keys:
  -
    - cross_target_platform
    - macos_machine
    - meson_cpu_family
    - uname_machine
    - uname_kernel_release
    - FINAL_PYTHON_SYSCONFIGDATA_NAME