MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [x86_64 and osx]
  - 11.3                                                    # [arm64 and osx]

python:
  - 3.9
  - 3.10
  - 3.11
  - 3.12

numpy:
  - 1.26
