mpi:
  - mpich  # [not win]

blas:
  - libblas  # [linux]
  - libaccelerate-osx  # [osx]

lapack:
  - liblapack  # [linux]
  - libaccelerate-osx  # [osx]

pin_run_as_build:
  parmetis:
    min_pin: x.x.x
    max_pin: x.x
  scalapack:
    min_pin: x.x.x
    max_pin: x.x
