{% set version = "5.5.1" %}
{% set build = 0 %}

package:
  name: mumps
  version: {{ version }}

source:
  url: http://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_{{ version }}.tar.gz
  sha256: 1abff294fa47ee4cfd50dfd5c595942b72ebfcedce08142a75a99ab35014fa15
  patches:
    - files/0001-fixing-shared-build.patch

build:
  number: 1
  script:
    - ${RECIPE_DIR}/build-mpi.sh
    - ${RECIPE_DIR}/build-headers.sh
  skip: true  # [win or osx]
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}

  {% set build_pin = '' %}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - m2-patch  # [win]
    - make  # [unix]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - metis 5.1.*
    - parmetis 4.0.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*
  run:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - metis 5.1.*
    - parmetis 4.0.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*

test:
  commands:
    {% for lib in [
      'smumps',
      'dmumps',
      'cmumps',
      'zmumps',
      'mumps_common',
      'pord',
    ] %}
    - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"
    {% endfor %}
    - test -f "${PREFIX}/include/mumps_compat.h"

about:
  home: http://mumps.enseeiht.fr/
  license: CECILL-C
  license_file: LICENSE
  summary: 'MUMPS: a parallel sparse direct solver'
  description: |
    MUMPS (MUltifrontal Massively Parallel Solver) is a package for solving
    systems of linear equations of the form Ax = b, where A is a square sparse
    matrix that can be either unsymmetric, symmetric positive definite, or
    general symmetric, on distributed memory computers. MUMPS implements a
    direct method based on a multifrontal approach which performs a Gaussian
    factorization.
  doc_url: http://mumps.enseeiht.fr/index.php?page=doc

extra:
  recipe-maintainers:
    - andrsd
