MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 10.15                                                   # [not arm64 and osx]
  - 11.3                                                    # [arm64 and osx]

blas:
  - libblas  # [linux]
  - libaccelerate-osx  # [osx]

cblas:
  - libcblas  # [linux]
  - libaccelerate-osx  # [osx]

python:
  - 3.9.*
  - 3.10.*
  - 3.11.*
