#!/bin/bash

CMAKE_BUILD_TYPE=Release

cmake_args=(
    ${CMAKE_ARGS}
    -DCMAKE_FIND_ROOT_PATH="${PREFIX};${BUILD_PREFIX};${BUILD_PREFIX}/${HOST}/sysroot"
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_PREFIX_PATH="${PREFIX}"
    -DCMAKE_INSTALL_PREFIX=${PREFIX}
    -DBUILD_SHARED_LIBS=ON
    -DVTK_BUILD_DOCUMENTATION=OFF
    -DVTK_BUILD_TESTING=OFF
    -DVTK_BUILD_EXAMPLES=OFF
    -DVTK_LEGACY_SILENT=OFF
    -DVTK_WRAP_PYTHON=ON
    -DVTK_WRAP_JAVA=OFF
    -DVTK_USE_MPI=ON
    -DVTK_USE_EXTERNAL=ON
    -DVTK_MODULE_ENABLE_VTK_CommonCore=YES
    -DVTK_MODULE_ENABLE_VTK_CommonDataModel=YES
    -DVTK_MODULE_ENABLE_VTK_FiltersCore=YES
    -DVTK_MODULE_ENABLE_VTK_FiltersGeneral=YES
    -DVTK_MODULE_ENABLE_VTK_IOCore=YES
    -DVTK_MODULE_ENABLE_VTK_IOEnSight=YES
    -DVTK_MODULE_ENABLE_VTK_IOExodus=YES
    -DVTK_MODULE_ENABLE_VTK_IOLegacy=YES
    -DVTK_MODULE_ENABLE_VTK_IOParallelXML=YES
    -DVTK_MODULE_ENABLE_VTK_IOXML=YES
    -DVTK_MODULE_ENABLE_VTK_IOXMLParser=YES
    -DVTK_MODULE_ENABLE_VTK_ParallelCore=YES
    -DVTK_MODULE_ENABLE_VTK_sqlite=NO
    -DVTK_MODULE_USE_EXTERNAL_VTK_cgns=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_doubleconversion=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_eigen=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_expat=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_exprtk=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_fast_float=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_fmt=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_verdict=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_freetype=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_glew=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_ioss=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_libharu=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_libxml2=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_lzma=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_mpi4py=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_pegtl=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_pugixml=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_sqlite=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_tiff=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_verdict=OFF
)

if [[ "$target_platform" == linux-* ]]
then
    cmake_args+=(
        "-DVTK_USE_X=OFF"
        "-DVTK_OPENGL_HAS_OSMESA=ON"
    )
fi

mkdir build
cd build
cmake ${cmake_args[@]} ${SRC_DIR}
make install -j${CPU_COUNT}
