#!/bin/bash

CMAKE_BUILD_TYPE=Release

cmake_args=(
    ${CMAKE_ARGS}
    -DCMAKE_FIND_ROOT_PATH="${PREFIX};${BUILD_PREFIX};${BUILD_PREFIX}/${HOST}/sysroot"
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_PREFIX_PATH="${PREFIX}"
    -DCMAKE_FIND_FRAMEWORK=LAST
    -DCMAKE_INSTALL_PREFIX=${PREFIX}
    -DCMAKE_INSTALL_RPATH="${PREFIX}/lib"
    -DCMAKE_INSTALL_LIBDIR=lib
    -DBUILD_SHARED_LIBS=ON
    -DVTK_BUILD_DOCUMENTATION=OFF
    -DVTK_BUILD_TESTING=OFF
    -DVTK_BUILD_EXAMPLES=OFF
    -DVTK_LEGACY_SILENT=OFF
    -DVTK_WRAP_PYTHON=ON
    -DVTK_WRAP_JAVA=OFF
    -DVTK_USE_MPI=ON
    -DVTK_GROUP_ENABLE_MPI=DEFAULT
    -DVTK_GROUP_ENABLE_Imaging=DEFAULT
    -DVTK_GROUP_ENABLE_MPI=DEFAULT
    -DVTK_GROUP_ENABLE_Qt=DONT_WANT
    -DVTK_GROUP_ENABLE_Rendering=DONT_WANT
    -DVTK_GROUP_ENABLE_StandAlone=WANT
    -DVTK_GROUP_ENABLE_Views=DEFAULT
    -DVTK_GROUP_ENABLE_Web=DEFAULT
    -DVTK_MODULE_ENABLE_VTK_sqlite=NO
    -DVTK_DATA_EXCLUDE_FROM_ALL=ON
    -DVTK_USE_EXTERNAL=ON
    -DVTK_MODULE_ENABLE_VTK_fmt=NO
    -DVTK_MODULE_USE_EXTERNAL_VTK_fast_float=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_libharu=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_pegtl=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_exprtk=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_fmt=ON
    -DVTK_MODULE_USE_EXTERNAL_VTK_cgns=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_ioss=OFF
    -DVTK_MODULE_USE_EXTERNAL_VTK_verdict=OFF
)

if [[ "$target_platform" == linux-* ]]
then
    cmake_args+=(
        "-DVTK_USE_X=OFF"
        "-DVTK_OPENGL_HAS_OSMESA=ON"
    )
fi

mkdir build
cd build
cmake ${cmake_args[@]} ${SRC_DIR}
make install -j${CPU_COUNT}
