{% set version = "9.3.0" %}
{% set build = 0 %}

package:
  name: vtk
  version: {{ version }}

source:
  url: https://www.vtk.org/files/release/9.3/VTK-{{ version }}.tar.gz
  sha256: fdc7b9295225b34e4fdddc49cd06e66e94260cb00efee456e0f66568c9681be9
  patches:
    - files/liblzma-fix.patch

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true # [win]

requirements:
  build:
    - cmake
    - make
    - python {{ python }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - mesalib  # [linux]
  run:
    - {{ mpi }}
    - python
    - mesalib  # [linux]

about:
  summary: |
    The Visualization Toolkit (VTK) is open source software for manipulating
    and displaying scientific data.

extra:
  recipe-maintainers:
    - andrsd
