{% set version = "9.3.0" %}
{% set parts = version.split(".") %}
{% set maj_min = parts[0] ~ "." ~ parts[1] %}
{% set build = 4 %}

package:
  name: vtk
  version: {{ version }}

source:
  url: https://www.vtk.org/files/release/{{ maj_min }}/VTK-{{ version }}.tar.gz
  sha256: fdc7b9295225b34e4fdddc49cd06e66e94260cb00efee456e0f66568c9681be9
  patches:
    - files/0001-liblzma-fix.patch
    - files/0002-exodusii-ex-utils.patch
    - files/0003-diy2-fmt.patch
    - files/0004-octree-fix.patch

build:
  number: {{ build }}
  string: {{ mpi }}_py{{ PY_VER.replace('.', '') }}h{{ PKG_HASH }}_{{ build }}
  skip: true # [win]

requirements:
  build:
    - cmake
    - make
    - python {{ python }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - mpi4py

  host:
    - python {{ python }}
    - zlib
    - freetype
    - hdf5 1.12.* {{ mpi }}_*
    - libxml2
    - libpng
    - libjpeg-turbo
    - libtiff
    - jsoncpp
    - expat
    - tbb
    - tbb-devel
    - libnetcdf 4.9.* {{ mpi }}_*
    - lz4-c
    - xorg-libxt  # [linux]
    - utfcpp
    - eigen 3.4.*
    - double-conversion
    - pugixml
    - glew
    - libogg
    - libtheora
    - nlohmann_json
    - proj
    - loguru
    - gl2ps
    - pugixml
    - mpi4py
    - fmt 9.*
    - mesalib 23.2.*   # [linux]
  run:
    - {{ mpi }}
    - python {{ python }}
    - zlib
    - freetype
    - hdf5 1.12.* {{ mpi }}_*
    - libxml2
    - libpng
    - libjpeg-turbo
    - libtiff
    - jsoncpp
    - expat
    - tbb
    - libnetcdf 4.9.* {{ mpi }}_*
    - lz4-c
    - utfcpp
    - eigen 3.4.*
    - double-conversion
    - pugixml
    - glew
    - libogg
    - libtheora
    - nlohmann_json
    - proj
    - loguru
    - gl2ps
    - tbb-devel
    - numpy
    - mpi4py
    - mesalib 23.2.*   # [linux]

test:
  commands:
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkNew.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkCommonCoreModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkCommonDataModelModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkFiltersCoreModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkIOCoreModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkIOExodusModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkIOEnSightModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkIOLegacyModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkIOParallelXMLModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkIOXMLModule.h
    - test -f $PREFIX/include/vtk-{{ maj_min }}/vtkIOParallelModule.h
    - test -f $PREFIX/lib/libvtkCommonCore-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkCommonDataModel-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkFiltersCore-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkIOCore-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkIOExodus-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkIOEnSight-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkIOLegacy-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkIOParallelXML-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkIOXML-{{ maj_min }}$SHLIB_EXT
    - test -f $PREFIX/lib/libvtkParallelCore-{{ maj_min }}$SHLIB_EXT

about:
  summary: |
    The Visualization Toolkit (VTK) is open source software for manipulating
    and displaying scientific data.

extra:
  recipe-maintainers:
    - andrsd
