{% set version = "3.21.2" %}
{% set build = 3 %}

{% set version_xy = version.rsplit(".", 1)[0] %}
{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: slepc
  version: {{ version }}

source:
  url: http://slepc.upv.es/download/distrib/slepc-{{ version }}.tar.gz
  sha256: 306fa649750509b3957b9f9311bff5dc1d20be5c5d494dd6472584c439b931f6

build:
  skip: true  # [win]
  number: {{ build }}
  string: {{ mpi }}_{{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('slepc', max_pin='x.x') }} {{ scalar }}_*
  track_features:
    - slepc_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - python
    - gnuconfig
    - {{ mpi }}
  host:
    - python
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - petsc {{ version_xy }}.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*
  run:
    - {{ mpi }}
    - {{ blas }}
    - {{ lapack }}
    - petsc {{ version_xy }}.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  files:
    - tests/test10.c
    - tests/Makefile
  commands:
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD-2-Clause
  license_file: LICENSE.md
  license_family: BSD

extra:
  recipe-maintainers:
    - andrsd
