{% set version = "3.18.3" %}
{% set build = 0 %}

{% set version_xy = version.rsplit(".", 1)[0] %}
{% set mpi = mpi or 'mpich' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: slepc
  version: {{ version }}

source:
  url: http://slepc.upv.es/download/distrib/slepc-{{ version }}.tar.gz
  sha256: 1b02bdf87c083749e81b3735aae7728098eaab78143b262b92c2ab164924c6f5

build:
  skip: true  # [win]
  number: {{ build }}
  string: {{ mpi }}_{{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('slepc', max_pin='x.x') }} {{ scalar }}_*
  track_features:
    - slepc_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - python
    - gnuconfig
    - {{ mpi }}
  host:
    - python
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - petsc {{ version_xy }}.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*
  run:
    - {{ mpi }}
    - {{ blas }}
    - {{ lapack }}
    - petsc {{ version_xy }}.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*

test:
  requires:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
  files:
    - tests/test10.c
    - tests/test14f.F
    - tests/Makefile
  commands:
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags slepc
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --libs   slepc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: BSD-2-Clause
  license_file: LICENSE.md
  license_family: BSD

extra:
  recipe-maintainers:
    - andrsd
