{% set name = "cargo-bundle-licenses" %}
{% set version = "4.0.0" %}
{% set build = 1 %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/sstadick/cargo-bundle-licenses/archive/v{{ version }}.tar.gz
  sha256: fc702051ed5556d88d20e93f14efb23cc257091046f47bb69e76363ecf6b4760

build:
  number: {{ build }}

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-auditable
    - pkg-config
    - make
    - cmake
    - libgit2
    - zlib
  host:
    - libgit2
    - zlib

tests:
  commands:
    - cargo-bundle-licenses --help

about:
  license: MIT
  license_file: LICENSE-MIT
  summary: Bundle thirdparty licenses for Cargo projects into a single file.
  homepage: https://github.com/sstadick/cargo-bundle-licenses

extra:
  recipe-maintainers:
    - andrsd
