{% set version = "5.0.8" %}
{% set major = version.rpartition('.')[0] %}
{% set build = 1000 %}

# give conda package a higher build number
{% if mpi_type == 'conda' %}
{% set build = build + 100 %}
{% endif %}

package:
  # must not match any outputs for requirements to be handled correctly
  name: openmpi-mpi
  version: {{ version }}

source:
  url: https://www.open-mpi.org/software/ompi/v{{ major }}/downloads/openmpi-{{ version }}.tar.bz2
  sha256: 53131e1a57e7270f645707f8b0b65ba56048f5b5ac3f68faabed3eb0d710e449

build:
  number: {{ build }}
  skip: true  # [win]

outputs:
  {% if mpi_type == 'conda' %}
  - name: openmpi
    script: build-mpi.sh
    build:
      run_exports:
        - {{ pin_subpackage('openmpi', min_pin='x.x.x', max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - pkg-config
        - make
        - shellcheck
      host:
        - libevent 2.1.*
        - libfabric-devel {{ libfabric }}.*
        - libhwloc 2.12.*
        - zlib 1.3.*
        - libnl 3.11.*                         # [linux]
        - ucc 1.6.*                            # [linux and not ppc64le]
        - ucx 1.18.*                           # [linux and not ppc64le]
      run:
        - zlib 1.3.*
        - mpi 1.0.* openmpi
    test:
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.sh

  - name: openmpi-mpicc
    build:
      script:
        - echo 'ok'  # [not osx]
    requirements:
      run:
        - {{ pin_subpackage('openmpi', exact=True) }}
        # host C compilers work fine (better) on mac
        - {{ compiler('c') }}
    test:
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.c

  - name: openmpi-mpicxx
    build:
      script:
        - echo 'ok'  # [not osx]
    requirements:
      run:
        - {{ pin_subpackage('openmpi', exact=True) }}
        # host C compilers work fine (better) on mac
        - {{ compiler('cxx') }}
    test:
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.cxx

  - name: openmpi-mpifort
    build:
      script:
        - echo 'ok'  # [not osx]
    requirements:
      run:
        - {{ pin_subpackage('openmpi', exact=True) }}
        - {{ compiler('fortran') }}
    test:
      script: run_test.sh
      files:
        - mpiexec.sh
        - tests/helloworld.f
        - tests/helloworld.f90
  {% else %}
  - name: openmpi
    build:
      string: {{ mpi_type }}_{{ build }}
      track_features:
        - openmpi_{{ mpi_type }}
    requirements:
      host: []
      run:
        - mpi 1.0 openmpi
    test:
      commands:
        - echo "It works!"
  {% endif %}

about:
  home: https://www.open-mpi.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source Message Passing Interface implementation.
  description: |
    The Open MPI Project is an open source Message Passing Interface
    implementation that is developed and maintained by a consortium of academic,
    research, and industry partners.
  doc_url: https://www.open-mpi.org/doc/
  dev_url: https://github.com/open-mpi/ompi

extra:
  recipe-maintainers:
    - andrsd
