{% set xorg_name = "inputproto" %}
{% set xorg_category = "proto" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "2.3.2" %}
{% set sha256 = "893a6af55733262058a27b38eeb1edc733669f01d404e8581b167f03c03ef31d" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1002
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf                   # [win]
    - m2-automake{{ am_version }}   # [win]
    - m2-libtool                    # [win]
    - m2w64-pkg-config              # [win]
    - pkg-config                    # [not win]
    - posix                         # [win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}           # [unix]
    - {{ compiler('m2w64_c') }}     # [win]
    - make                          # [unix]
    - autoconf                      # [unix]
    - automake                      # [unix]
    - gettext                       # [unix]
    - libtool                       # [unix]
  host:
    - xorg-util-macros

test:
  commands:

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'C prototypes for the XInput extension.'

extra:
  recipe-maintainers:
    - pkgw
