{% set version = "3.21.6" %}
{% set build = 2 %}

package:
  name: petsc
  version: {{ version }}

source:
  url: https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-{{ version }}.tar.gz
  sha256: cb2dc00742a89cf8acf9ff8aae189e6864e8b90f4997f087be6e54ff39c30d74

build:
  skip: true  # [win]
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  number: {{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
    - pkg-config
    - python {{ python }}
    - gnuconfig  # [unix]
    - {{ mpi }}
  host:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - libhwloc
    - zlib
    - hdf5 1.12.* {{ mpi }}_*
    - exodusii 2022.10.* {{ mpi }}_*
    - ptscotch 7.0.* {{ mpi }}_*
    - metis 5.1.0.p11
    - parmetis 4.0.* {{ mpi }}_*
    - hypre 2.29.* {{ mpi }}_*
  run:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - libhwloc
    - zlib
    - hdf5 1.12.* {{ mpi }}_*
    - exodusii 2022.08.* {{ mpi }}_*
    - ptscotch 7.0.* {{ mpi }}_*
    - metis 5.1.0.p11
    - parmetis 4.0.* {{ mpi }}_*
    - hypre 2.29.* {{ mpi }}_*

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc
    - test -f $PREFIX/lib/libpetsc$SHLIB_EXT
    - test -f $PREFIX/include/petsc.h

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - andrsd
