{% set version = "3.19.4" %}
{% set build = 0 %}

package:
  name: petsc
  version: {{ version }}

source:
  url: https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-{{ version }}.tar.gz
  sha256: 7c941b71be52c3b764214e492df60109d12f97f7d854c97a44df0c4d958b3906

build:
  skip: true  # [win]
  number: {{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - cmake
    - pkg-config
    - python {{ python }}
    - gnuconfig  # [unix]
    - {{ mpi }}
  host:
    - libblas
    - libcblas
    - liblapack
    - {{ mpi }}
    - zlib
    - hdf5 1.12.* mpi_mpich_*
    - scalapack 2.2.*
    - exodusii 2022.08.*
  run:
    - libblas
    - libcblas
    - liblapack
    - {{ mpi }}
    - zlib
    - hdf5 1.12.* mpi_mpich_*
    - scalapack 2.2.*
    - exodusii 2022.08.*

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc
    - test -f $PREFIX/lib/libpetsc$SHLIB_EXT
    - test -f $PREFIX/include/petsc.h

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - andrsd
