{% set version = "3.18.6" %}
{% set build = 5 %}

package:
  name: petsc
  version: {{ version }}

source:
  url: https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-{{ version }}.tar.gz
  sha256: 8b53c8b6652459ba0bbe6361b5baf8c4d17c1d04b6654a76e3b6a9ab4a576680

build:
  skip: true  # [win]
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  number: {{ build }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - cmake
    - pkg-config
    - python {{ python }}
    - gnuconfig  # [unix]
    - {{ mpi }}
  host:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - zlib
    - hdf5 1.12.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*
    - exodusii 2022.08.* {{ mpi }}_*
    - ptscotch 7.0.* {{ mpi }}_*
    - metis 5.1.0-p*
    - parmetis 4.0.* {{ mpi }}_*
    - hypre 2.25.*  {{ mpi }}_*
    - viennacl 1.7.*
  run:
    - {{ blas }}
    - {{ lapack }}
    - {{ mpi }}
    - zlib
    - hdf5 1.12.* {{ mpi }}_*
    - scalapack 2.2.* {{ mpi }}_*
    - exodusii 2022.08.* {{ mpi }}_*
    - ptscotch 7.0.* {{ mpi }}_*
    - metis 5.1.*
    - parmetis 4.0.* {{ mpi }}_*
    - hypre 2.25.* {{ mpi }}_*
    - viennacl 1.7.*

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc
    - test -f $PREFIX/lib/libpetsc$SHLIB_EXT
    - test -f $PREFIX/include/petsc.h

about:
  home: https://www.mcs.anl.gov/petsc/
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://gitlab.com/petsc/petsc
  doc_url: https://petsc.org/release/docs/manual/

extra:
  recipe-maintainers:
    - andrsd
