{% set version = "3.6.00" %}
{% set build = 0 %}

package:
  name: kokkos
  version: {{ version }}

source:
  url: https://github.com/kokkos/kokkos/archive/refs/tags/{{ version }}.tar.gz
  sha256: 53b11fffb53c5d48da5418893ac7bc814ca2fde9c86074bdfeaa967598c918f4

build:
  number: {{ build }}
  string: {{ mpi }}_h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make
    - {{ mpi }}
  host:
    - {{ mpi }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

test:
  commands:
    - test -f $PREFIX/include/KokkosCore_config.h
    - test -f $PREFIX/lib/libkokkoscore.dylib  # [osx]
    - test -f $PREFIX/lib/libkokkoscore.so  # [linux]

about:
  home: https://kokkos.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Kokkos C++ Performance Portability Programming Ecosystem: The Programming
    Model - Parallel Execution and Memory Abstraction
  description: |
    Kokkos Core implements a programming model in C++ for writing performance
    portable applications targeting all major HPC platforms. For that purpose
    it provides abstractions for both parallel execution of code and data
    management. Kokkos is designed to target complex node architectures with
    N-level memory hierarchies and multiple types of execution resources. It
    currently can use CUDA, HIP, SYCL, HPX, OpenMP and C++ threads as backend
    programming models with several other backends in development.
  dev_url: https://github.com/kokkos/kokkos
  doc_url: https://kokkos.org/kokkos-core-wiki/

extra:
  recipe-maintainers:
    - andrsd
