name: "Build package: breathe"

on:
  pull_request:
    branches:
      - main
      - petsc-*
    paths:
      - recipes/breathe/meta.yaml

jobs:
  build:
    uses: ./.github/workflows/pkg-build.yml
    with:
      package-name: breathe
    secrets: inherit
