name: "Deploy package: exodusII"

on:
  push:
    branches:
      - petsc-*
    paths:
      - recipes/exodusii/meta.yaml

jobs:
  build:
    uses: ./.github/workflows/pkg-deploy.yml
    with:
      package-name: exodusii
    secrets: inherit
