name: "Build package: MUMPS"

on:
  push:
    branches:
      - main
    paths:
      - recipes/mumps/meta.yaml

jobs:
  build:
    uses: ./.github/workflows/pkg-build.yml
    with:
      package-name: mumps
      upload: true
    secrets: inherit
