name: "Deploy package: ParMETIS"

on:
  push:
    branches:
      - main
    paths:
      - recipes/parmetis/meta.yaml

jobs:
  build:
    uses: ./.github/workflows/pkg-deploy.yml
    with:
      package-name: parmetis
    secrets: inherit
