name: "Build package: PETSc"

on:
  push:
    branches:
      - main
    paths:
      - recipes/petsc/meta.yaml

jobs:
  build:
    uses: ./.github/workflows/pkg-build.yml
    with:
      package-name: petsc
      upload: true
    secrets: inherit
