on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
    secrets:
      ANACONDA_TOKEN:
        required: true

jobs:
  deploy:
    name: "${{ inputs.package-name }}"
    defaults:
      run:
        shell: bash -el {0}

    runs-on: ubuntu-22.04
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          auto-update-conda: false
          channels: ${{ vars.CHANNEL_NAME }},main
          channel-priority: flexible

      - name: Install prerequisites
        run: |
          conda install anaconda-client

      - name: Build
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} move \
            --from-label devel \
            --to-label main \
            ${{ vars.CHANNEL_NAME }}/${{ inputs.package-name }} 
