on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
    secrets:
      ANACONDA_TOKEN:
        required: true

jobs:
  build:
    name: "${{ matrix.os }}, py-${{ matrix.python-version }}"
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-22.04'
            python-version: '3.9'
          - os: 'macos-12'
            python-version: '3.9'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: false
          channels: ${{ vars.CHANNEL_NAME }},main
          channel-priority: strict

      - name: Install prerequisites
        run: |
          conda install \
            conda-build \
            conda-verify \
            anaconda-client

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build
        run: |
          conda-build recipes/${{ inputs.package-name }} \
            --user ${{ vars.CHANNEL_NAME }} \
            --token ${{ secrets.ANACONDA_TOKEN }} \
            --label devel
