on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
    secrets:
      ANACONDA_TOKEN:
        required: true

jobs:
  build:
    defaults:
      run:
        shell: bash -el {0}

    runs-on: ubuntu-22.04
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: false
          channels: ${{ vars.CHANNEL_NAME }},conda-forge,defaults
          channel-priority: strict
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install prerequisites
        run: |
          mamba install anaconda-client

      - name: Build
        run: |
          anaconda move \
            --token ${{ secrets.ANACONDA_TOKEN }} \
            --from-label devel \
            --to-label main \
            ${{ vars.CHANNEL_NAME }}/${{ inputs.package-name }} 
