{% set version = "1.0.0" %}
{% set build = 0 %}

package:
  name: libaccelerate-osx
  version: {{ version }}

build:
  number: "{{ build }}"
  skip: true  # [linux or win]

about:
  summary: |
    Meta-package for Apple-shipped Accelerate framework

extra:
  recipe-maintainers:
    - andrsd
